### ISSUE TITLE
Can't create or open existing files nor create new projects if QtCreator is current editor

### ISSUE THREAD

**Issue by silvanocerza** [xBazilio/UE4_Win_QtCreatorSourceCodeAccess#5] opened 2018-07-31 21:46 UTC
I've found several issues, these are the steps to reproduce them. Hope it helps. :)

`C:\Qt\`, `C:\Qt\Tools\QtCreator\` and `C:\Qt\Tools\QtCreator\bin\` are all in my `PATH`.

Issue 1:
1. Load a project 
2. Set "Source Code Editor" to "Visual Studio 2017"
3. Close and reopen project
4. Set "Source Code Editor" to "Qt Creator 4.x"
5. Close and reopen project
6. Create new C++ class
This is the result, changing back to "Visual Studio 2017" doesn't resolve the issue, you must close and reopen the project.
![image](https://user-images.githubusercontent.com/3314350/43488507-5261a1c0-951a-11e8-9ca0-16f31a5b27a5.png)

Issue 2:
1. Load a project 
2. Set "Source Code Editor" to "Visual Studio 2017"
3. Close and reopen project
4. Set "Source Code Editor" to "Qt Creator 4.x"
5. Create a new C++ class
6. Class is created but not opened in Qt Creator

Issue 3:
1. Load a project 
2. Set "Source Code Editor" to "Visual Studio 2017"
3. Close and reopen project
4. Set "Source Code Editor" to "Qt Creator 4.x"
5. Double click on existing C++ class to open it
6. This message is returned in Output Log
```
LogAssetEditorManager: Opening Asset editor for Class /Script/MyProject.MyPawn
LogQtCreatorAccessor: Warning: FQtCreatorSourceCodeAccessor::OpenSourceFiles: cannot find Qt Creator
```

Issue 4:
1. Load a project 
2. Set "Source Code Editor" to "Visual Studio 2017"
3. Close and reopen project
4. Set "Source Code Editor" to "Qt Creator 4.x"
5. Close and reopen project
5. Double click on existing C++ class to open it
6. This message is returned in Output Log
```
LogSlate: Took 0.000207 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Light.ttf' (167K)
LogAssetEditorManager: Opening Asset editor for Class /Script/MyProject.MyPawn
LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: 'Engine/Tutorial/Installation/InstallingVisualStudioTutorial' is not a standard unreal filename or a long path name. Reason: Path should start with a '/'
LogLinker: Warning: Can't find file 'Engine/Tutorial/Installation/InstallingVisualStudioTutorial'
LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: 'Engine/Tutorial/Installation/InstallingVisualStudioTutorial' is not a standard unreal filename or a long path name. Reason: Path should start with a '/'
LogLinker: Warning: Can't find file 'Engine/Tutorial/Installation/InstallingVisualStudioTutorial'
LogUObjectGlobals: Warning: Failed to find object 'Blueprint Engine/Tutorial/Installation/InstallingVisualStudioTutorial.InstallingVisualStudioTutorial'
```

Issue 5:
1. Load a project 
2. Set "Source Code Editor" to "Visual Studio 2017"
3. Close and reopen project
4. Set "Source Code Editor" to "Qt Creator 4.x"
5. Close project
6. Create new project
This message is shown.
![image](https://user-images.githubusercontent.com/3314350/43488937-976d5092-951b-11e8-9a77-bed442958a98.png)

**Comment by xBazilio** [comment] 2018-08-04 08:26
Hi!

> C:\Qt\, C:\Qt\Tools\QtCreator\ and C:\Qt\Tools\QtCreator\bin\ are all in my PATH.

There is no need for this. The plugin finds Qt Creator assuming it is installed in the default path.

Issues 1-4:
Don't see the point in switching edidor to VS 2017 and back to Qt Creator. However did as you said and couldn't reproduse.
Qt Creator opens, classes are created.

Issue 5:
Does not relate to Qt Creator. Try opening VS 2017, update it, login in to it, etc. It's a Microsoft stuff.

Did you update UE to 4.20.1? I've tested all of these in 4.20.1all work like a charm.

**Comment by silvanocerza** [comment] 2018-08-05 19:10
I've tried adding those directories to PATH hoping Qt Creator would be found since it returned this error:
```
LogQtCreatorAccessor: Warning: FQtCreatorSourceCodeAccessor::OpenSourceFiles: cannot find Qt Creator
```

Last issue happens only if the current editor for UE is Qt Creator, if it's set to VS 2017 it works just fine.

I was already on UE 4.20.1 and just updated to latest VS 2017 version but nothing changed.

**Comment by xBazilio** [comment] 2018-08-06 06:58
I have Qt Creator in `c:\Qt\qtcreator-4.5.2\bin\qtcreator.exe`
And older one in `c:\Qt\Tools\QtCreator\bin\qtcreator.exe`
Both can be found by the plugin.

**Comment by xBazilio** [comment] 2018-08-13 09:55
@Alien1993, did you manage to get it working?

**Comment by silvanocerza** [comment] 2018-08-13 09:57
Nope, I don't know what might be the issue.

**Comment by xBazilio** [comment] 2018-08-13 10:21
Share with me your example project, I'll try to reproduce.
Did you try to create new C++ project and using the plugin with it?
Also give me the paths in witch your projects are located.
And I assume you have qtcreator installed as a part of QT library. Wich version of qtcreator do you have?

**Comment by silvanocerza** [comment] 2018-08-13 16:48
I can't create a new C++ project with the plugin enabled because the error at issue 5 is shown. 

My projects are saved in `C:\Users\The Alien\UnrealProjects`.

Here a sample project I just created, I first selected Visual Studio 2017 to create it and then switched back to Qt Creator.
https://github.com/Alien1993/QtTest

Yes, Qt Creator has been installed with Qt on the default path "C:\Qt".
Qt Creator version:
```
Qt Creator 4.7.0
Based on Qt 5.11.1 (MSVC 2015, 32 bit)

Built on Jul 17 2018 04:27:33

From revision dedbb40f57

Copyright 2008-2018 The Qt Company Ltd. All rights reserved.

The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.```

**Comment by xBazilio** [comment] 2018-08-13 18:56
Can't reproduce anything.
You have a space in your projects path. Try using path without spaces in it. For example `C:\UnrealProjects`.
My projects are saved in `d:\Bazilio\unreal\Projects`.

**Comment by silvanocerza** [comment] 2018-08-13 19:30
Just tried and nothing changes. I declare myself defeated.

**Comment by xBazilio** [comment] 2018-09-29 19:30
@Alien1993, when you got message "No compiler found", did you try to press "Install Visual Studio" button?
I've just had this issue. I pressed this button, VS updated and error message disappeared.

**Comment by silvanocerza** [comment] 2018-09-29 20:00
I did. Can't remember if it said that it was already updated or if it let me update, otherwise it kept giving me the same error.

**Comment by xBazilio** [comment] 2018-09-29 20:26
And another bit of advise, that can help:
https://forums.unrealengine.com/development-discussion/c-gameplay-programming/1483633-ue4-keeps-trying-to-use-visual-studio-2015-when-2017-is-installed-can-t-start-new-projects
post about editing %appdata%\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml
Mine was in c:\Users\Bazilio\AppData\Roaming\Unreal Engine\UnrealBuildTool\

The thing is, UE compiles project using VS, no matter what do you use as an editor.

I've just had issue, and couldn't create new C++ class. This helped me.

**Comment by xBazilio** [comment] 2018-09-29 20:35
And don't use latest QtCreator for editing UE code. 4.7 complains alot about parse errors. I use 4.6.2 and it's ok.

**Comment by xBazilio** [comment] 2018-10-27 16:56
@Alien1993, Hi again!
As you can see I've been able to reproduce and solve your issues. And it has nothing to do with the plugin. I'm closing this issue. If you have any problems, please let me know.

**Closed as completed by xBazilio** 2018-10-27 16:56 UTC

**Comment by silvanocerza** [comment] 2018-10-27 20:42
No problem, thanks for the help. Sorry I forgot to answer earlier.
